### PR TITLE
Added Image and Team Card for Alex Guba, CoZ Developer

### PR DESCRIPTION
**Pull request by gubanotorious**

### CODE REVIEW

**Comment by chenzhitong** [comment]
Your github account does not belong to the CoZ organization.

**Comment by gubanotorious** [comment]
This is corrected, please check again?

**Comment by chenzhitong** [comment]
You can invite other CoZ members to review @gubanotorious

**Comment by AshRolls** [comment]
Hi @chenzhitong. @gubanotorious is a valid member of CoZ, please refer to https://github.com/orgs/CityOfZion/people

**Pull request closed without merging**
