### PR TITLE
Added Christopher Colomb to Team page

### PR DESCRIPTION
**Pull request by kurisu1996**

### CODE REVIEW

**Comment by chenzhitong** [comment]
“NEO Japan Founder” This title is inappropriate. In addition, please send me your translated article, I confirm it.

**Comment by chenzhitong** [comment]
“NEO Japan Founder” This title is inappropriate. In addition, please send me your translated article, I confirm it. @kurisu1996

**Comment by kurisu1996** [comment]
Hello, chenzhitong. My apologies for not providing an explanation upon PR creation.

NEO Japan is a community I founded in June 2017 to provide Japanese translations to NEO and projects built upon the NEO blockchain. Our goal is to expand the Japanese NEO community with our contributions.

Here are our NEO documentation published works:
- *NEO - General and Technical Documents (total of 156 documents)
  - GitHub Link: https://github.com/neo-project/docs/tree/master/ja-jp
  - Published Link: http://docs.neo.org/ja-jp/index.html
*Upon translating the documents, we formatted and created necessary images and directories for the GitHub document repositories for easy implementation to the website. GitHub Pull Requests are created by NEO Japan, and the NEO Docs Repository Manager merges the PR upon review approval.

**Comment by chenzhitong** [comment]
The name Neo Japan is ambiguous, and it will make people realize that it is not a community organization, but NEO's official organization. Title only write “City of Zion Translator”, how about it. @kurisu1996

**Comment by kurisu1996** [comment]
@chenzhitong Understood. I realize the confusion this may cause. I am okay with "City of Zion Translator".

**Pull request merged**
